project:
  type: website

website:
  title: " Gergő Bocsárdi | <sub> <sup> data science, networks & a sprinkle of chaos </sup> </sub>" 
  favicon: resources/logo.png
  description: "data science, networks & a sprinkle of chaos"


  navbar:
    # title: "Gergő Bocsárdi"
    # style: "floating"
    logo: resources/logo.png
    tools:
      - icon: share
        href: https://bsky.app/profile/agbocsardi.com
      - icon: instagram
        href: https://www.instagram.com/gergo.jpeg/
      - icon: youtube
        href: https://www.youtube.com/@agbocsardi

    # search: true

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Get to know me"
        contents:
          - photography.qmd
          # - coffee.qmd
      - section: "Research"
        contents:
          - research.qmd
          # - publications.qmd


format:
  html:
    theme:
      light: [default, resources/style/light.scss]
      dark: [default, resources/style/dark.scss]
    css: resources/style/styles.css
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    mainfont: "Roboto Slab"
  



